// Generate vocabulary JSON file with 500+ Chinese-Khmer words
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const words = [
  // ===== FOOD (食物) =====
  {id:1,chinese:"苹果",pinyin:"píng guǒ",khmer:"ផ្លែប៉ោម",emoji:"🍎",category:"food",hsk:1,example_cn:"我每天都吃一个苹果。",example_km:"ខ្ញុំញ៉ាំផ្លែប៉ោមមួយគ្រាប់រៀងរាល់ថ្ងៃ។"},
  {id:2,chinese:"水",pinyin:"shuǐ",khmer:"ទឹក",emoji:"💧",category:"food",hsk:1,example_cn:"请给我一杯水。",example_km:"សូមឱ្យខ្ញុំទឹកមួយកែវ។"},
  {id:3,chinese:"米饭",pinyin:"mǐ fàn",khmer:"បាយ",emoji:"🍚",category:"food",hsk:1,example_cn:"中国人喜欢吃米饭。",example_km:"ជនជាតិចិនចូលចិត្តញ៉ាំបាយ។"},
  {id:4,chinese:"茶",pinyin:"chá",khmer:"តែ",emoji:"🍵",category:"food",hsk:1,example_cn:"我喜欢喝中国茶。",example_km:"ខ្ញុំចូលចិត្តផឹកតែចិន។"},
  {id:5,chinese:"咖啡",pinyin:"kā fēi",khmer:"កាហ្វេ",emoji:"☕",category:"food",hsk:2,example_cn:"我每天早上喝一杯咖啡。",example_km:"ខ្ញុំផឹកកាហ្វេមួយពែងរៀងរាល់ព្រឹក។"},
  {id:6,chinese:"面条",pinyin:"miàn tiáo",khmer:"មី",emoji:"🍜",category:"food",hsk:2,example_cn:"这碗面条很好吃。",example_km:"មីចានមួយនេះឆ្ងាញ់ណាស់។"},
  {id:7,chinese:"鸡蛋",pinyin:"jī dàn",khmer:"ស៊ុត",emoji:"🥚",category:"food",hsk:2,example_cn:"早餐我吃了两个鸡蛋。",example_km:"អាហារពេលព្រឹកខ្ញុំញ៉ាំស៊ុតពីរគ្រាប់។"},
  {id:8,chinese:"鸡肉",pinyin:"jī ròu",khmer:"សាច់មាន់",emoji:"🍗",category:"food",hsk:2,example_cn:"我喜欢吃鸡肉。",example_km:"ខ្ញុំចូលចិត្តញ៉ាំសាច់មាន់។"},
  {id:9,chinese:"牛奶",pinyin:"niú nǎi",khmer:"ទឹកដោះគោ",emoji:"🥛",category:"food",hsk:2,example_cn:"孩子们每天喝牛奶。",example_km:"ក្មេងៗផឹកទឹកដោះគោរៀងរាល់ថ្ងៃ។"},
  {id:10,chinese:"面包",pinyin:"miàn bāo",khmer:"នំប៉័ង",emoji:"🍞",category:"food",hsk:2,example_cn:"我早餐吃面包。",example_km:"ខ្ញុំញ៉ាំនំប៉័ងពេលព្រឹក។"},
  {id:11,chinese:"蔬菜",pinyin:"shū cài",khmer:"បន្លែ",emoji:"🥬",category:"food",hsk:2,example_cn:"多吃蔬菜对身体好。",example_km:"ញ៉ាំបន្លែច្រើនល្អសម្រាប់រាងកាយ។"},
  {id:12,chinese:"水果",pinyin:"shuǐ guǒ",khmer:"ផ្លែឈើ",emoji:"🍉",category:"food",hsk:1,example_cn:"柬埔寨的水果很甜。",example_km:"ផ្លែឈើកម្ពុជាផ្អែមណាស់។"},
  {id:13,chinese:"香蕉",pinyin:"xiāng jiāo",khmer:"ចេក",emoji:"🍌",category:"food",hsk:3,example_cn:"猴子喜欢吃香蕉。",example_km:"ស្វាចូលចិត្តញ៉ាំចេក។"},
  {id:14,chinese:"西瓜",pinyin:"xī guā",khmer:"ឪឡឹក",emoji:"🍉",category:"food",hsk:3,example_cn:"夏天吃西瓜很凉快。",example_km:"ញ៉ាំឪឡឹកពេលរដូវក្ដៅត្រជាក់ណាស់។"},
  {id:15,chinese:"牛肉",pinyin:"niú ròu",khmer:"សាច់គោ",emoji:"🥩",category:"food",hsk:3,example_cn:"这家餐厅的牛肉很好吃。",example_km:"សាច់គោនៅភោជនីយដ្ឋាននេះឆ្ងាញ់ណាស់។"},
  {id:16,chinese:"猪肉",pinyin:"zhū ròu",khmer:"សាច់ជ្រូក",emoji:"🥓",category:"food",hsk:3,example_cn:"猪肉是中国人常吃的肉。",example_km:"សាច់ជ្រូកជាសាច់ដែលជនជាតិចិនតែងញ៉ាំ។"},
  {id:17,chinese:"鱼",pinyin:"yú",khmer:"ត្រី",emoji:"🐟",category:"food",hsk:1,example_cn:"我喜欢吃鱼。",example_km:"ខ្ញុំចូលចិត្តញ៉ាំត្រី។"},
  {id:18,chinese:"盐",pinyin:"yán",khmer:"អំបិល",emoji:"🧂",category:"food",hsk:3,example_cn:"这道菜盐放多了。",example_km:"ម្ហូបនេះដាក់អំបិលច្រើនពេក។"},
  {id:19,chinese:"糖",pinyin:"táng",khmer:"ស្ករ",emoji:"🍬",category:"food",hsk:3,example_cn:"少吃糖对牙齿好。",example_km:"ញ៉ាំស្ករតិចល្អសម្រាប់ធ្មេញ។"},
  {id:20,chinese:"饺子",pinyin:"jiǎo zi",khmer:"ប៉ៃឆា៎ូ",emoji:"🥟",category:"food",hsk:3,example_cn:"过年的时候要吃饺子。",example_km:"ពេលចូលឆ្នាំត្រូវញ៉ាំប៉ៃឆា៎ូ។"},
  {id:21,chinese:"豆腐",pinyin:"dòu fu",khmer:"តៅហ៊ូ",emoji:"🧈",category:"food",hsk:4,example_cn:"豆腐营养很丰富。",example_km:"តៅហ៊ូមានអាហារូបត្ថម្ភច្រើន។"},
  {id:22,chinese:"啤酒",pinyin:"pí jiǔ",khmer:"ស្រាបៀរ",emoji:"🍺",category:"food",hsk:3,example_cn:"天气热的时候喝啤酒很舒服。",example_km:"ផឹកស្រាបៀរពេលអាកាសធាតុក្ដៅស្រួលណាស់។"},
  // ===== ANIMALS (动物) =====
  {id:23,chinese:"猫",pinyin:"māo",khmer:"ឆ្មា",emoji:"🐱",category:"animals",hsk:1,example_cn:"这只猫很可爱。",example_km:"ឆ្មានេះគួរឱ្យស្រឡាញ់ណាស់។"},
  {id:24,chinese:"狗",pinyin:"gǒu",khmer:"ឆ្កែ",emoji:"🐕",category:"animals",hsk:1,example_cn:"他有一只大狗。",example_km:"គាត់មានឆ្កែធំមួយក្បាល។"},
  {id:25,chinese:"鸟",pinyin:"niǎo",khmer:"បក្សី",emoji:"🐦",category:"animals",hsk:2,example_cn:"树上有很多鸟。",example_km:"នៅលើដើមឈើមានបក្សីច្រើន។"},
  {id:26,chinese:"马",pinyin:"mǎ",khmer:"សេះ",emoji:"🐴",category:"animals",hsk:3,example_cn:"他会骑马。",example_km:"គាត់ចេះជិះសេះ។"},
  {id:27,chinese:"牛",pinyin:"niú",khmer:"គោ",emoji:"🐄",category:"animals",hsk:3,example_cn:"农民养了很多牛。",example_km:"កសិករចិញ្ចឹមគោច្រើន។"},
  {id:28,chinese:"猪",pinyin:"zhū",khmer:"ជ្រូក",emoji:"🐷",category:"animals",hsk:3,example_cn:"猪很聪明。",example_km:"ជ្រូកឆ្លាតណាស់។"},
  {id:29,chinese:"羊",pinyin:"yáng",khmer:"ចៀម",emoji:"🐑",category:"animals",hsk:3,example_cn:"山上有很多羊。",example_km:"នៅលើភ្នំមានចៀមច្រើន។"},
  {id:30,chinese:"蛇",pinyin:"shé",khmer:"ពស់",emoji:"🐍",category:"animals",hsk:4,example_cn:"我很怕蛇。",example_km:"ខ្ញុំខ្លាចពស់ណាស់។"},
  {id:31,chinese:"大象",pinyin:"dà xiàng",khmer:"ដំរី",emoji:"🐘",category:"animals",hsk:4,example_cn:"大象是很大的动物。",example_km:"ដំរីជាសត្វធំណាស់។"},
  {id:32,chinese:"老虎",pinyin:"lǎo hǔ",khmer:"ខ្លា",emoji:"🐅",category:"animals",hsk:4,example_cn:"老虎是森林之王。",example_km:"ខ្លាជាស្ដេចនៃព្រៃ។"},
  {id:33,chinese:"兔子",pinyin:"tù zi",khmer:"ទន្សាយ",emoji:"🐰",category:"animals",hsk:3,example_cn:"兔子喜欢吃胡萝卜。",example_km:"ទន្សាយចូលចិត្តញ៉ាំការ៉ុត។"},
  {id:34,chinese:"猴子",pinyin:"hóu zi",khmer:"ស្វា",emoji:"🐒",category:"animals",hsk:3,example_cn:"猴子很聪明。",example_km:"ស្វាឆ្លាតណាស់។"},
  // ===== TRANSPORT (交通) =====
  {id:35,chinese:"车",pinyin:"chē",khmer:"ឡាន",emoji:"🚗",category:"transport",hsk:1,example_cn:"我开车去上班。",example_km:"ខ្ញុំបើកឡានទៅធ្វើការ។"},
  {id:36,chinese:"公共汽车",pinyin:"gōng gòng qì chē",khmer:"រថយន្តក្រុង",emoji:"🚌",category:"transport",hsk:2,example_cn:"我坐公共汽车去上班。",example_km:"ខ្ញុំជិះរថយន្តក្រុងទៅធ្វើការ។"},
  {id:37,chinese:"出租车",pinyin:"chū zū chē",khmer:"តាក់ស៊ី",emoji:"🚕",category:"transport",hsk:2,example_cn:"我坐出租车去机场。",example_km:"ខ្ញុំជិះតាក់ស៊ីទៅព្រលានយន្តហោះ។"},
  {id:38,chinese:"飞机",pinyin:"fēi jī",khmer:"យន្តហោះ",emoji:"✈️",category:"transport",hsk:2,example_cn:"坐飞机去北京要三个小时。",example_km:"ជិះយន្តហោះទៅប៉េកាំងត្រូវការបីម៉ោង។"},
  {id:39,chinese:"火车",pinyin:"huǒ chē",khmer:"រថភ្លើង",emoji:"🚂",category:"transport",hsk:2,example_cn:"中国的火车很快。",example_km:"រថភ្លើងចិនលឿនណាស់។"},
  {id:40,chinese:"自行车",pinyin:"zì xíng chē",khmer:"កង់",emoji:"🚲",category:"transport",hsk:2,example_cn:"我骑自行车去学校。",example_km:"ខ្ញុំជិះកង់ទៅសាលារៀន។"},
  {id:41,chinese:"船",pinyin:"chuán",khmer:"ទូក",emoji:"🚢",category:"transport",hsk:3,example_cn:"我们坐船过河。",example_km:"យើងជិះទូកឆ្លងទន្លេ។"},
  {id:42,chinese:"摩托车",pinyin:"mó tuō chē",khmer:"ម៉ូតូ",emoji:"🏍️",category:"transport",hsk:4,example_cn:"柬埔寨很多人骑摩托车。",example_km:"មនុស្សច្រើនជិះម៉ូតូនៅកម្ពុជា។"},
  // ===== BODY (身体) =====
  {id:43,chinese:"头",pinyin:"tóu",khmer:"ក្បាល",emoji:"🗣️",category:"body",hsk:2,example_cn:"我头疼。",example_km:"ខ្ញុំឈឺក្បាល។"},
  {id:44,chinese:"眼睛",pinyin:"yǎn jing",khmer:"ភ្នែក",emoji:"👁️",category:"body",hsk:2,example_cn:"她的眼睛很大。",example_km:"ភ្នែករបស់នាងធំណាស់។"},
  {id:45,chinese:"耳朵",pinyin:"ěr duo",khmer:"ត្រចៀក",emoji:"👂",category:"body",hsk:3,example_cn:"兔子的耳朵很长。",example_km:"ត្រចៀកទន្សាយវែងណាស់។"},
  {id:46,chinese:"嘴",pinyin:"zuǐ",khmer:"មាត់",emoji:"👄",category:"body",hsk:3,example_cn:"不要用嘴说别人坏话。",example_km:"កុំនិយាយអាក្រក់ពីអ្នកដទៃ។"},
  {id:47,chinese:"手",pinyin:"shǒu",khmer:"ដៃ",emoji:"✋",category:"body",hsk:1,example_cn:"请洗手。",example_km:"សូមលាងដៃ។"},
  {id:48,chinese:"脚",pinyin:"jiǎo",khmer:"ជើង",emoji:"🦶",category:"body",hsk:2,example_cn:"走了很多路，脚很累。",example_km:"ដើរច្រើនហើយ ជើងនឿយណាស់។"},
  {id:49,chinese:"心",pinyin:"xīn",khmer:"បេះដូង",emoji:"❤️",category:"body",hsk:2,example_cn:"我心里很开心。",example_km:"ក្នុងចិត្តខ្ញុំសប្បាយណាស់។"},
  {id:50,chinese:"鼻子",pinyin:"bí zi",khmer:"ច្រមុះ",emoji:"👃",category:"body",hsk:3,example_cn:"他的鼻子很高。",example_km:"ច្រមុះរបស់គាត់ខ្ពស់ណាស់។"},
  // ===== FAMILY (家庭) =====
  {id:51,chinese:"爸爸",pinyin:"bà ba",khmer:"ប៉ា",emoji:"👨",category:"family",hsk:1,example_cn:"我爸爸是老师。",example_km:"ប៉ាខ្ញុំជាគ្រូបង្រៀន។"},
  {id:52,chinese:"妈妈",pinyin:"mā ma",khmer:"ម៉ាក់",emoji:"👩",category:"family",hsk:1,example_cn:"妈妈做的饭很好吃。",example_km:"បាយដែលម៉ាក់ធ្វើឆ្ងាញ់ណាស់។"},
  {id:53,chinese:"哥哥",pinyin:"gē ge",khmer:"បង​ប្រុស",emoji:"👦",category:"family",hsk:2,example_cn:"我哥哥比我大三岁。",example_km:"បងប្រុសខ្ញុំធំជាងខ្ញុំបីឆ្នាំ។"},
  {id:54,chinese:"姐姐",pinyin:"jiě jie",khmer:"បង​ស្រី",emoji:"👧",category:"family",hsk:2,example_cn:"我姐姐在大学读书。",example_km:"បងស្រីខ្ញុំរៀននៅសកលវិទ្យាល័យ។"},
  {id:55,chinese:"弟弟",pinyin:"dì di",khmer:"ប្អូន​ប្រុស",emoji:"👦",category:"family",hsk:2,example_cn:"我弟弟今年十岁。",example_km:"ប្អូនប្រុសខ្ញុំអាយុដប់ឆ្នាំ។"},
  {id:56,chinese:"妹妹",pinyin:"mèi mei",khmer:"ប្អូន​ស្រី",emoji:"👧",category:"family",hsk:2,example_cn:"我妹妹很聪明。",example_km:"ប្អូនស្រីខ្ញុំឆ្លាតណាស់។"},
  {id:57,chinese:"爷爷",pinyin:"yé ye",khmer:"តា",emoji:"👴",category:"family",hsk:3,example_cn:"爷爷今年八十岁了。",example_km:"តាអាយុប៉ែតសិបឆ្នាំហើយ។"},
  {id:58,chinese:"奶奶",pinyin:"nǎi nai",khmer:"យាយ",emoji:"👵",category:"family",hsk:3,example_cn:"奶奶很喜欢做饭。",example_km:"យាយចូលចិត្តធ្វើម្ហូបណាស់។"},
  {id:59,chinese:"丈夫",pinyin:"zhàng fu",khmer:"ប្ដី",emoji:"👨",category:"family",hsk:3,example_cn:"她的丈夫是医生。",example_km:"ប្ដីរបស់នាងជាវេជ្ជបណ្ឌិត។"},
  {id:60,chinese:"妻子",pinyin:"qī zi",khmer:"ប្រពន្ធ",emoji:"👩",category:"family",hsk:3,example_cn:"他的妻子很漂亮。",example_km:"ប្រពន្ធរបស់គាត់ស្រស់ស្អាតណាស់។"},
  {id:61,chinese:"儿子",pinyin:"ér zi",khmer:"កូន​ប្រុស",emoji:"👦",category:"family",hsk:2,example_cn:"他的儿子在上学。",example_km:"កូនប្រុសគាត់កំពុងរៀន។"},
  {id:62,chinese:"女儿",pinyin:"nǚ ér",khmer:"កូន​ស្រី",emoji:"👧",category:"family",hsk:2,example_cn:"她的女儿三岁了。",example_km:"កូនស្រីនាងអាយុបីឆ្នាំហើយ។"},
  // ===== NUMBERS (数字) =====
  {id:63,chinese:"一",pinyin:"yī",khmer:"មួយ",emoji:"1️⃣",category:"numbers",hsk:1,example_cn:"我有一个苹果。",example_km:"ខ្ញុំមានផ្លែប៉ោមមួយ។"},
  {id:64,chinese:"二",pinyin:"èr",khmer:"ពីរ",emoji:"2️⃣",category:"numbers",hsk:1,example_cn:"我有两个孩子。",example_km:"ខ្ញុំមានកូនពីរនាក់។"},
  {id:65,chinese:"三",pinyin:"sān",khmer:"បី",emoji:"3️⃣",category:"numbers",hsk:1,example_cn:"三个人一起去。",example_km:"បីនាក់ទៅជាមួយគ្នា។"},
  {id:66,chinese:"十",pinyin:"shí",khmer:"ដប់",emoji:"🔟",category:"numbers",hsk:1,example_cn:"十个人都来了。",example_km:"ដប់នាក់មកគ្រប់គ្នាហើយ។"},
  {id:67,chinese:"百",pinyin:"bǎi",khmer:"រយ",emoji:"💯",category:"numbers",hsk:2,example_cn:"这件衣服一百块钱。",example_km:"អាវនេះតម្លៃមួយរយយាន។"},
  {id:68,chinese:"千",pinyin:"qiān",khmer:"ពាន់",emoji:"🔢",category:"numbers",hsk:2,example_cn:"这本书一千块钱。",example_km:"សៀវភៅនេះតម្លៃមួយពាន់យាន។"},
  // ===== COLORS (颜色) =====
  {id:69,chinese:"红色",pinyin:"hóng sè",khmer:"ពណ៌ក្រហម",emoji:"🔴",category:"colors",hsk:1,example_cn:"中国人喜欢红色。",example_km:"ជនជាតិចិនចូលចិត្តពណ៌ក្រហម។"},
  {id:70,chinese:"蓝色",pinyin:"lán sè",khmer:"ពណ៌ខៀវ",emoji:"🔵",category:"colors",hsk:2,example_cn:"天空是蓝色的。",example_km:"មេឃមានពណ៌ខៀវ។"},
  {id:71,chinese:"绿色",pinyin:"lǜ sè",khmer:"ពណ៌បៃតង",emoji:"🟢",category:"colors",hsk:2,example_cn:"草是绿色的。",example_km:"ស្មៅមានពណ៌បៃតង។"},
  {id:72,chinese:"白色",pinyin:"bái sè",khmer:"ពណ៌ស",emoji:"⚪",category:"colors",hsk:2,example_cn:"雪是白色的。",example_km:"ព្រិលមានពណ៌ស។"},
  {id:73,chinese:"黑色",pinyin:"hēi sè",khmer:"ពណ៌ខ្មៅ",emoji:"⚫",category:"colors",hsk:2,example_cn:"她穿了黑色的裙子。",example_km:"នាងពាក់សំពត់ពណ៌ខ្មៅ។"},
  {id:74,chinese:"黄色",pinyin:"huáng sè",khmer:"ពណ៌លឿង",emoji:"🟡",category:"colors",hsk:2,example_cn:"香蕉是黄色的。",example_km:"ចេកមានពណ៌លឿង។"},
  // ===== PROFESSIONS (职业) =====
  {id:75,chinese:"老师",pinyin:"lǎo shī",khmer:"គ្រូបង្រៀន",emoji:"👩‍🏫",category:"professions",hsk:1,example_cn:"我的老师很好。",example_km:"គ្រូបង្រៀនរបស់ខ្ញុំល្អណាស់។"},
  {id:76,chinese:"医生",pinyin:"yī shēng",khmer:"វេជ្ជបណ្ឌិត",emoji:"👨‍⚕️",category:"professions",hsk:2,example_cn:"她是一位好医生。",example_km:"នាងជាវេជ្ជបណ្ឌិតល្អម្នាក់។"},
  {id:77,chinese:"学生",pinyin:"xué shēng",khmer:"សិស្ស",emoji:"👨‍🎓",category:"professions",hsk:1,example_cn:"我是一个学生。",example_km:"ខ្ញុំជាសិស្សម្នាក់។"},
  {id:78,chinese:"司机",pinyin:"sī jī",khmer:"អ្នកបើកបរ",emoji:"🚗",category:"professions",hsk:3,example_cn:"出租车司机很热情。",example_km:"អ្នកបើកតាក់ស៊ីរួសរាយណាស់។"},
  {id:79,chinese:"厨师",pinyin:"chú shī",khmer:"ចុងភៅ",emoji:"👨‍🍳",category:"professions",hsk:4,example_cn:"这个厨师做的菜很好吃。",example_km:"ម្ហូបដែលចុងភៅនេះធ្វើឆ្ងាញ់ណាស់។"},
  {id:80,chinese:"警察",pinyin:"jǐng chá",khmer:"ប៉ូលីស",emoji:"👮",category:"professions",hsk:3,example_cn:"警察保护我们的安全。",example_km:"ប៉ូលីសការពារសុវត្ថិភាពយើង។"},
  {id:81,chinese:"护士",pinyin:"hù shi",khmer:"គិលានុបដ្ឋាយិកា",emoji:"👩‍⚕️",category:"professions",hsk:3,example_cn:"护士照顾病人。",example_km:"គិលានុបដ្ឋាយិកាមើលថែអ្នកជំងឺ។"},
  {id:82,chinese:"工人",pinyin:"gōng rén",khmer:"កម្មករ",emoji:"👷",category:"professions",hsk:3,example_cn:"工人在建房子。",example_km:"កម្មករកំពុងសង់ផ្ទះ។"},
  // ===== GREETINGS (问候) =====
  {id:83,chinese:"你好",pinyin:"nǐ hǎo",khmer:"សួស្តី",emoji:"👋",category:"greetings",hsk:1,example_cn:"你好，很高兴认识你。",example_km:"សួស្តី រីករាយដែលបានស្គាល់។"},
  {id:84,chinese:"谢谢",pinyin:"xiè xie",khmer:"អរគុណ",emoji:"🙏",category:"greetings",hsk:1,example_cn:"谢谢你的帮助。",example_km:"អរគុណសម្រាប់ជំនួយរបស់អ្នក។"},
  {id:85,chinese:"再见",pinyin:"zài jiàn",khmer:"លាហើយ",emoji:"👋",category:"greetings",hsk:1,example_cn:"明天见，再见！",example_km:"ជួបគ្នាថ្ងៃស្អែក លាហើយ!"},
  {id:86,chinese:"对不起",pinyin:"duì bu qǐ",khmer:"សូមទោស",emoji:"😔",category:"greetings",hsk:1,example_cn:"对不起，我迟到了。",example_km:"សូមទោស ខ្ញុំមកយឺតហើយ។"},
  {id:87,chinese:"没关系",pinyin:"méi guān xi",khmer:"មិនអីទេ",emoji:"😊",category:"greetings",hsk:1,example_cn:"没关系，别担心。",example_km:"មិនអីទេ កុំបារម្ភ។"},
  {id:88,chinese:"请",pinyin:"qǐng",khmer:"សូម",emoji:"🤝",category:"greetings",hsk:1,example_cn:"请坐。",example_km:"សូមអង្គុយ។"},
  // ===== TIME (时间) =====
  {id:89,chinese:"今天",pinyin:"jīn tiān",khmer:"ថ្ងៃនេះ",emoji:"📅",category:"time",hsk:1,example_cn:"今天天气很好。",example_km:"ថ្ងៃនេះអាកាសធាតុល្អណាស់។"},
  {id:90,chinese:"明天",pinyin:"míng tiān",khmer:"ថ្ងៃស្អែក",emoji:"📆",category:"time",hsk:1,example_cn:"明天我去上班。",example_km:"ថ្ងៃស្អែកខ្ញុំទៅធ្វើការ។"},
  {id:91,chinese:"昨天",pinyin:"zuó tiān",khmer:"ម្សិលមិញ",emoji:"⏪",category:"time",hsk:1,example_cn:"昨天下雨了。",example_km:"ម្សិលមិញភ្លៀងធ្លាក់។"},
  {id:92,chinese:"早上",pinyin:"zǎo shang",khmer:"ពេលព្រឹក",emoji:"🌅",category:"time",hsk:1,example_cn:"早上好！",example_km:"អរុណសួស្តី!"},
  {id:93,chinese:"晚上",pinyin:"wǎn shang",khmer:"ពេលយប់",emoji:"🌙",category:"time",hsk:1,example_cn:"晚上我看电视。",example_km:"ពេលយប់ខ្ញុំមើលទូរទស្សន៍។"},
  {id:94,chinese:"现在",pinyin:"xiàn zài",khmer:"ឥឡូវ",emoji:"⏰",category:"time",hsk:1,example_cn:"现在几点了？",example_km:"ឥឡូវម៉ោងប៉ុន្មានហើយ?"},
  {id:95,chinese:"星期",pinyin:"xīng qī",khmer:"សប្ដាហ៍",emoji:"📅",category:"time",hsk:1,example_cn:"一个星期有七天。",example_km:"មួយសប្ដាហ៍មានប្រាំពីរថ្ងៃ។"},
  {id:96,chinese:"月",pinyin:"yuè",khmer:"ខែ",emoji:"🗓️",category:"time",hsk:1,example_cn:"一年有十二个月。",example_km:"មួយឆ្នាំមានដប់ពីរខែ។"},
  {id:97,chinese:"年",pinyin:"nián",khmer:"ឆ្នាំ",emoji:"🎆",category:"time",hsk:1,example_cn:"今年是2026年。",example_km:"ឆ្នាំនេះជាឆ្នាំ 2026។"},
  // ===== PLACES (地方) =====
  {id:98,chinese:"家",pinyin:"jiā",khmer:"ផ្ទះ",emoji:"🏠",category:"places",hsk:1,example_cn:"我在家休息。",example_km:"ខ្ញុំសម្រាកនៅផ្ទះ។"},
  {id:99,chinese:"学校",pinyin:"xué xiào",khmer:"សាលារៀន",emoji:"🏫",category:"places",hsk:1,example_cn:"我们的学校很大。",example_km:"សាលារៀនរបស់យើងធំណាស់។"},
  {id:100,chinese:"医院",pinyin:"yī yuàn",khmer:"មន្ទីរពេទ្យ",emoji:"🏥",category:"places",hsk:2,example_cn:"他在医院工作。",example_km:"គាត់ធ្វើការនៅមន្ទីរពេទ្យ។"},
  {id:101,chinese:"银行",pinyin:"yín háng",khmer:"ធនាគារ",emoji:"🏦",category:"places",hsk:3,example_cn:"我去银行取钱。",example_km:"ខ្ញុំទៅធនាគារដកលុយ។"},
  {id:102,chinese:"超市",pinyin:"chāo shì",khmer:"ផ្សារទំនើប",emoji:"🏪",category:"places",hsk:3,example_cn:"我在超市买东西。",example_km:"ខ្ញុំទិញឥវ៉ាន់នៅផ្សារទំនើប។"},
  {id:103,chinese:"餐厅",pinyin:"cān tīng",khmer:"ភោជនីយដ្ឋាន",emoji:"🍽️",category:"places",hsk:2,example_cn:"这家餐厅的菜很好吃。",example_km:"ម្ហូបនៅភោជនីយដ្ឋាននេះឆ្ងាញ់ណាស់។"},
  {id:104,chinese:"机场",pinyin:"jī chǎng",khmer:"ព្រលានយន្តហោះ",emoji:"🛫",category:"places",hsk:3,example_cn:"我们在机场见面。",example_km:"យើងជួបគ្នានៅព្រលានយន្តហោះ។"},
  {id:105,chinese:"公园",pinyin:"gōng yuán",khmer:"សួន​សាធារណៈ",emoji:"🌳",category:"places",hsk:3,example_cn:"我们去公园散步。",example_km:"យើងទៅដើរលេងនៅសួនសាធារណៈ។"},
  {id:106,chinese:"商店",pinyin:"shāng diàn",khmer:"ហាង",emoji:"🏬",category:"places",hsk:2,example_cn:"这家商店很大。",example_km:"ហាងនេះធំណាស់។"},
  // ===== ACTIONS (动作) =====
  {id:107,chinese:"吃",pinyin:"chī",khmer:"ញ៉ាំ",emoji:"🍽️",category:"actions",hsk:1,example_cn:"我们一起吃饭吧。",example_km:"យើងញ៉ាំបាយជាមួយគ្នា។"},
  {id:108,chinese:"喝",pinyin:"hē",khmer:"ផឹក",emoji:"🥤",category:"actions",hsk:1,example_cn:"多喝水对身体好。",example_km:"ផឹកទឹកច្រើនល្អសម្រាប់រាងកាយ។"},
  {id:109,chinese:"看",pinyin:"kàn",khmer:"មើល",emoji:"👀",category:"actions",hsk:1,example_cn:"我在看书。",example_km:"ខ្ញុំកំពុងមើលសៀវភៅ។"},
  {id:110,chinese:"听",pinyin:"tīng",khmer:"ស្ដាប់",emoji:"👂",category:"actions",hsk:1,example_cn:"我喜欢听音乐。",example_km:"ខ្ញុំចូលចិត្តស្ដាប់តន្ត្រី។"},
  {id:111,chinese:"说",pinyin:"shuō",khmer:"និយាយ",emoji:"💬",category:"actions",hsk:1,example_cn:"请说慢一点。",example_km:"សូមនិយាយយឺតៗ។"},
  {id:112,chinese:"写",pinyin:"xiě",khmer:"សរសេរ",emoji:"✍️",category:"actions",hsk:1,example_cn:"我在写作业。",example_km:"ខ្ញុំកំពុងសរសេរកិច្ចការ។"},
  {id:113,chinese:"读",pinyin:"dú",khmer:"អាន",emoji:"📖",category:"actions",hsk:1,example_cn:"我喜欢读书。",example_km:"ខ្ញុំចូលចិត្តអានសៀវភៅ។"},
  {id:114,chinese:"走",pinyin:"zǒu",khmer:"ដើរ",emoji:"🚶",category:"actions",hsk:1,example_cn:"我们走吧。",example_km:"យើងទៅ។"},
  {id:115,chinese:"跑",pinyin:"pǎo",khmer:"រត់",emoji:"🏃",category:"actions",hsk:2,example_cn:"他跑得很快。",example_km:"គាត់រត់លឿនណាស់។"},
  {id:116,chinese:"买",pinyin:"mǎi",khmer:"ទិញ",emoji:"🛒",category:"actions",hsk:1,example_cn:"我想买这个。",example_km:"ខ្ញុំចង់ទិញនេះ។"},
  {id:117,chinese:"卖",pinyin:"mài",khmer:"លក់",emoji:"💰",category:"actions",hsk:2,example_cn:"他在市场卖水果。",example_km:"គាត់លក់ផ្លែឈើនៅផ្សារ។"},
  {id:118,chinese:"工作",pinyin:"gōng zuò",khmer:"ធ្វើការ",emoji:"💼",category:"actions",hsk:1,example_cn:"我在公司工作。",example_km:"ខ្ញុំធ្វើការនៅក្រុមហ៊ុន។"},
  {id:119,chinese:"学习",pinyin:"xué xí",khmer:"រៀន",emoji:"📚",category:"actions",hsk:1,example_cn:"我在学习中文。",example_km:"ខ្ញុំកំពុងរៀនភាសាចិន។"},
  {id:120,chinese:"睡觉",pinyin:"shuì jiào",khmer:"គេង",emoji:"😴",category:"actions",hsk:1,example_cn:"晚上十点我睡觉。",example_km:"ម៉ោងដប់យប់ខ្ញុំគេង។"},
  {id:121,chinese:"起床",pinyin:"qǐ chuáng",khmer:"ភ្ញាក់ពីគេង",emoji:"⏰",category:"actions",hsk:2,example_cn:"我每天六点起床。",example_km:"ខ្ញុំភ្ញាក់ពីគេងម៉ោង៦រៀងរាល់ថ្ងៃ។"},
  {id:122,chinese:"唱歌",pinyin:"chàng gē",khmer:"ច្រៀង",emoji:"🎤",category:"actions",hsk:2,example_cn:"她唱歌唱得很好。",example_km:"នាងច្រៀងពិរោះណាស់។"},
  {id:123,chinese:"跳舞",pinyin:"tiào wǔ",khmer:"រាំ",emoji:"💃",category:"actions",hsk:3,example_cn:"柬埔寨的传统舞蹈很美。",example_km:"របាំប្រពៃណីកម្ពុជាស្រស់ស្អាតណាស់។"},
  {id:124,chinese:"游泳",pinyin:"yóu yǒng",khmer:"ហែលទឹក",emoji:"🏊",category:"actions",hsk:3,example_cn:"夏天我喜欢游泳。",example_km:"រដូវក្ដៅខ្ញុំចូលចិត្តហែលទឹក។"},
  // ===== ADJECTIVES (形容词) =====
  {id:125,chinese:"大",pinyin:"dà",khmer:"ធំ",emoji:"⬆️",category:"adjectives",hsk:1,example_cn:"这个房间很大。",example_km:"បន្ទប់នេះធំណាស់។"},
  {id:126,chinese:"小",pinyin:"xiǎo",khmer:"តូច",emoji:"⬇️",category:"adjectives",hsk:1,example_cn:"这只猫很小。",example_km:"ឆ្មានេះតូចណាស់។"},
  {id:127,chinese:"好",pinyin:"hǎo",khmer:"ល្អ",emoji:"👍",category:"adjectives",hsk:1,example_cn:"你真好。",example_km:"អ្នកល្អណាស់។"},
  {id:128,chinese:"多",pinyin:"duō",khmer:"ច្រើន",emoji:"➕",category:"adjectives",hsk:1,example_cn:"人很多。",example_km:"មនុស្សច្រើនណាស់។"},
  {id:129,chinese:"少",pinyin:"shǎo",khmer:"តិច",emoji:"➖",category:"adjectives",hsk:1,example_cn:"人很少。",example_km:"មនុស្សតិចណាស់។"},
  {id:130,chinese:"漂亮",pinyin:"piào liang",khmer:"ស្រស់ស្អាត",emoji:"🌸",category:"adjectives",hsk:2,example_cn:"这个女孩很漂亮。",example_km:"ក្មេងស្រីនេះស្រស់ស្អាតណាស់។"},
  {id:131,chinese:"高兴",pinyin:"gāo xìng",khmer:"សប្បាយ",emoji:"😊",category:"adjectives",hsk:1,example_cn:"认识你很高兴。",example_km:"រីករាយដែលបានស្គាល់អ្នក។"},
  {id:132,chinese:"快",pinyin:"kuài",khmer:"លឿន",emoji:"⚡",category:"adjectives",hsk:1,example_cn:"他走得很快。",example_km:"គាត់ដើរលឿនណាស់។"},
  {id:133,chinese:"慢",pinyin:"màn",khmer:"យឺត",emoji:"🐌",category:"adjectives",hsk:2,example_cn:"请说慢一点。",example_km:"សូមនិយាយយឺតៗ។"},
  {id:134,chinese:"新",pinyin:"xīn",khmer:"ថ្មី",emoji:"✨",category:"adjectives",hsk:2,example_cn:"我买了一件新衣服。",example_km:"ខ្ញុំបានទិញអាវថ្មីមួយ។"},
  {id:135,chinese:"旧",pinyin:"jiù",khmer:"ចាស់",emoji:"📦",category:"adjectives",hsk:3,example_cn:"这是一本旧书。",example_km:"នេះជាសៀវភៅចាស់មួយ។"},
  {id:136,chinese:"贵",pinyin:"guì",khmer:"ថ្លៃ",emoji:"💎",category:"adjectives",hsk:2,example_cn:"这个太贵了。",example_km:"នេះថ្លៃពេកហើយ។"},
  {id:137,chinese:"便宜",pinyin:"pián yi",khmer:"ថោក",emoji:"💲",category:"adjectives",hsk:2,example_cn:"这个很便宜。",example_km:"នេះថោកណាស់។"},
  {id:138,chinese:"冷",pinyin:"lěng",khmer:"ត្រជាក់",emoji:"❄️",category:"adjectives",hsk:1,example_cn:"冬天很冷。",example_km:"រដូវរងារត្រជាក់ណាស់។"},
  {id:139,chinese:"热",pinyin:"rè",khmer:"ក្ដៅ",emoji:"🔥",category:"adjectives",hsk:1,example_cn:"今天很热。",example_km:"ថ្ងៃនេះក្ដៅណាស់។"},
  {id:140,chinese:"忙",pinyin:"máng",khmer:"រវល់",emoji:"🏃",category:"adjectives",hsk:2,example_cn:"我最近很忙。",example_km:"ខ្ញុំរវល់ណាស់ពេលនេះ។"},
  // ===== WEATHER (天气) =====
  {id:141,chinese:"天气",pinyin:"tiān qì",khmer:"អាកាសធាតុ",emoji:"🌤️",category:"weather",hsk:1,example_cn:"今天天气很好。",example_km:"ថ្ងៃនេះអាកាសធាតុល្អណាស់។"},
  {id:142,chinese:"下雨",pinyin:"xià yǔ",khmer:"ភ្លៀង",emoji:"🌧️",category:"weather",hsk:1,example_cn:"今天下雨了。",example_km:"ថ្ងៃនេះភ្លៀងធ្លាក់ហើយ។"},
  {id:143,chinese:"太阳",pinyin:"tài yáng",khmer:"ព្រះអាទិត្យ",emoji:"☀️",category:"weather",hsk:2,example_cn:"太阳出来了。",example_km:"ព្រះអាទិត្យរះហើយ។"},
  {id:144,chinese:"风",pinyin:"fēng",khmer:"ខ្យល់",emoji:"💨",category:"weather",hsk:3,example_cn:"今天风很大。",example_km:"ថ្ងៃនេះខ្យល់បក់ខ្លាំងណាស់។"},
  {id:145,chinese:"云",pinyin:"yún",khmer:"ពពក",emoji:"☁️",category:"weather",hsk:3,example_cn:"天上有很多云。",example_km:"នៅលើមេឃមានពពកច្រើន។"},
  {id:146,chinese:"雪",pinyin:"xuě",khmer:"ព្រិល",emoji:"❄️",category:"weather",hsk:3,example_cn:"北京冬天会下雪。",example_km:"ប៉េកាំងរដូវរងារមានព្រិលធ្លាក់។"},
  // ===== TECHNOLOGY (科技) =====
  {id:147,chinese:"手机",pinyin:"shǒu jī",khmer:"ទូរស័ព្ទ",emoji:"📱",category:"technology",hsk:2,example_cn:"我的手机没电了。",example_km:"ទូរស័ព្ទខ្ញុំអស់ថ្មហើយ។"},
  {id:148,chinese:"电脑",pinyin:"diàn nǎo",khmer:"កុំព្យូទ័រ",emoji:"💻",category:"technology",hsk:2,example_cn:"我用电脑工作。",example_km:"ខ្ញុំប្រើកុំព្យូទ័រធ្វើការ។"},
  {id:149,chinese:"电视",pinyin:"diàn shì",khmer:"ទូរទស្សន៍",emoji:"📺",category:"technology",hsk:2,example_cn:"晚上我看电视。",example_km:"ពេលយប់ខ្ញុំមើលទូរទស្សន៍។"},
  {id:150,chinese:"网络",pinyin:"wǎng luò",khmer:"អ៊ីនធឺណិត",emoji:"🌐",category:"technology",hsk:4,example_cn:"这里的网络很快。",example_km:"អ៊ីនធឺណិតនៅទីនេះលឿនណាស់។"},
  {id:151,chinese:"照片",pinyin:"zhào piàn",khmer:"រូបថត",emoji:"📷",category:"technology",hsk:3,example_cn:"我们一起拍照片吧。",example_km:"យើងថតរូបជាមួយគ្នា។"},
  // ===== SCHOOL (学校) =====
  {id:152,chinese:"书",pinyin:"shū",khmer:"សៀវភៅ",emoji:"📕",category:"school",hsk:1,example_cn:"这本书很有意思。",example_km:"សៀវភៅនេះគួរឱ្យចាប់អារម្មណ៍ណាស់។"},
  {id:153,chinese:"笔",pinyin:"bǐ",khmer:"ប៊ិច",emoji:"✏️",category:"school",hsk:2,example_cn:"请给我一支笔。",example_km:"សូមឱ្យខ្ញុំប៊ិចមួយ។"},
  {id:154,chinese:"字",pinyin:"zì",khmer:"អក្សរ",emoji:"🔤",category:"school",hsk:1,example_cn:"汉字很难写。",example_km:"អក្សរចិនពិបាកសរសេរ។"},
  {id:155,chinese:"考试",pinyin:"kǎo shì",khmer:"ប្រឡង",emoji:"📝",category:"school",hsk:2,example_cn:"明天有考试。",example_km:"ថ្ងៃស្អែកមានប្រឡង។"},
  {id:156,chinese:"作业",pinyin:"zuò yè",khmer:"កិច្ចការផ្ទះ",emoji:"📋",category:"school",hsk:2,example_cn:"我在做作业。",example_km:"ខ្ញុំកំពុងធ្វើកិច្ចការផ្ទះ។"},
  {id:157,chinese:"教室",pinyin:"jiào shì",khmer:"បន្ទប់រៀន",emoji:"🏫",category:"school",hsk:3,example_cn:"我们在教室上课。",example_km:"យើងរៀននៅក្នុងបន្ទប់រៀន។"},
  // ===== CLOTHES (衣服) =====
  {id:158,chinese:"衣服",pinyin:"yī fu",khmer:"សម្លៀកបំពាក់",emoji:"👕",category:"clothes",hsk:2,example_cn:"这件衣服很漂亮。",example_km:"សម្លៀកបំពាក់នេះស្រស់ស្អាតណាស់។"},
  {id:159,chinese:"裤子",pinyin:"kù zi",khmer:"ខោ",emoji:"👖",category:"clothes",hsk:3,example_cn:"这条裤子太长了。",example_km:"ខោនេះវែងពេក។"},
  {id:160,chinese:"鞋子",pinyin:"xié zi",khmer:"ស្បែកជើង",emoji:"👟",category:"clothes",hsk:3,example_cn:"我买了一双新鞋子。",example_km:"ខ្ញុំទិញស្បែកជើងថ្មីមួយគូ។"},
  {id:161,chinese:"帽子",pinyin:"mào zi",khmer:"មួក",emoji:"🧢",category:"clothes",hsk:3,example_cn:"天气热要戴帽子。",example_km:"អាកាសធាតុក្ដៅត្រូវពាក់មួក។"},
  // ===== EMOTIONS (情感) =====
  {id:162,chinese:"开心",pinyin:"kāi xīn",khmer:"រីករាយ",emoji:"😊",category:"emotions",hsk:2,example_cn:"今天我很开心。",example_km:"ថ្ងៃនេះខ្ញុំរីករាយណាស់។"},
  {id:163,chinese:"难过",pinyin:"nán guò",khmer:"ក្រៀមក្រំ",emoji:"😢",category:"emotions",hsk:3,example_cn:"他很难过。",example_km:"គាត់ក្រៀមក្រំណាស់។"},
  {id:164,chinese:"害怕",pinyin:"hài pà",khmer:"ខ្លាច",emoji:"😨",category:"emotions",hsk:3,example_cn:"小孩子害怕黑暗。",example_km:"ក្មេងៗខ្លាចងងឹត។"},
  {id:165,chinese:"生气",pinyin:"shēng qì",khmer:"ខឹង",emoji:"😡",category:"emotions",hsk:2,example_cn:"不要生气了。",example_km:"កុំខឹងអី។"},
  {id:166,chinese:"爱",pinyin:"ài",khmer:"ស្រឡាញ់",emoji:"❤️",category:"emotions",hsk:2,example_cn:"我爱我的家人。",example_km:"ខ្ញុំស្រឡាញ់គ្រួសាររបស់ខ្ញុំ។"},
  {id:167,chinese:"喜欢",pinyin:"xǐ huan",khmer:"ចូលចិត្ត",emoji:"💕",category:"emotions",hsk:1,example_cn:"我喜欢中国文化。",example_km:"ខ្ញុំចូលចិត្តវប្បធម៌ចិន។"},
  // ===== NATURE (自然) =====
  {id:168,chinese:"山",pinyin:"shān",khmer:"ភ្នំ",emoji:"⛰️",category:"nature",hsk:2,example_cn:"这座山很高。",example_km:"ភ្នំនេះខ្ពស់ណាស់។"},
  {id:169,chinese:"河",pinyin:"hé",khmer:"ទន្លេ",emoji:"🏞️",category:"nature",hsk:3,example_cn:"这条河很长。",example_km:"ទន្លេនេះវែងណាស់។"},
  {id:170,chinese:"海",pinyin:"hǎi",khmer:"សមុទ្រ",emoji:"🌊",category:"nature",hsk:3,example_cn:"柬埔寨有美丽的海。",example_km:"កម្ពុជាមានសមុទ្រស្រស់ស្អាត។"},
  {id:171,chinese:"树",pinyin:"shù",khmer:"ដើមឈើ",emoji:"🌳",category:"nature",hsk:2,example_cn:"公园里有很多树。",example_km:"នៅក្នុងសួនមានដើមឈើច្រើន។"},
  {id:172,chinese:"花",pinyin:"huā",khmer:"ផ្កា",emoji:"🌸",category:"nature",hsk:2,example_cn:"这朵花很漂亮。",example_km:"ផ្កានេះស្រស់ស្អាតណាស់។"},
  {id:173,chinese:"月亮",pinyin:"yuè liang",khmer:"ព្រះច័ន្ទ",emoji:"🌙",category:"nature",hsk:3,example_cn:"今晚的月亮很圆。",example_km:"ព្រះច័ន្ទយប់នេះមូលណាស់។"},
  {id:174,chinese:"星星",pinyin:"xīng xing",khmer:"ផ្កាយ",emoji:"⭐",category:"nature",hsk:3,example_cn:"天上有很多星星。",example_km:"នៅលើមេឃមានផ្កាយច្រើន។"},
  // ===== HOUSE (房子) =====
  {id:175,chinese:"门",pinyin:"mén",khmer:"ទ្វារ",emoji:"🚪",category:"house",hsk:2,example_cn:"请关门。",example_km:"សូមបិទទ្វារ។"},
  {id:176,chinese:"窗户",pinyin:"chuāng hu",khmer:"បង្អួច",emoji:"🪟",category:"house",hsk:3,example_cn:"请打开窗户。",example_km:"សូមបើកបង្អួច។"},
  {id:177,chinese:"桌子",pinyin:"zhuō zi",khmer:"តុ",emoji:"🪑",category:"house",hsk:2,example_cn:"桌子上有一本书。",example_km:"នៅលើតុមានសៀវភៅមួយ។"},
  {id:178,chinese:"椅子",pinyin:"yǐ zi",khmer:"កៅអី",emoji:"💺",category:"house",hsk:2,example_cn:"请坐椅子。",example_km:"សូមអង្គុយកៅអី។"},
  {id:179,chinese:"床",pinyin:"chuáng",khmer:"គ្រែ",emoji:"🛏️",category:"house",hsk:3,example_cn:"我买了一张新床。",example_km:"ខ្ញុំទិញគ្រែថ្មីមួយ។"},
  {id:180,chinese:"厕所",pinyin:"cè suǒ",khmer:"បន្ទប់ទឹក",emoji:"🚻",category:"house",hsk:3,example_cn:"厕所在哪儿？",example_km:"បន្ទប់ទឹកនៅណា?"},
  // ===== DAILY ITEMS (日用品) =====
  {id:181,chinese:"钱",pinyin:"qián",khmer:"លុយ",emoji:"💰",category:"daily_items",hsk:1,example_cn:"这个多少钱？",example_km:"នេះថ្លៃប៉ុន្មាន?"},
  {id:182,chinese:"钥匙",pinyin:"yào shi",khmer:"កូនសោ",emoji:"🔑",category:"daily_items",hsk:3,example_cn:"我的钥匙找不到了。",example_km:"ខ្ញុំរកកូនសោមិនឃើញ។"},
  {id:183,chinese:"包",pinyin:"bāo",khmer:"កាបូប",emoji:"👜",category:"daily_items",hsk:3,example_cn:"这个包很好看。",example_km:"កាបូបនេះស្រស់ស្អាតណាស់។"},
  {id:184,chinese:"伞",pinyin:"sǎn",khmer:"ឆត្រ",emoji:"☂️",category:"daily_items",hsk:3,example_cn:"下雨了，带伞吧。",example_km:"ភ្លៀងធ្លាក់ហើយ យកឆត្រទៅ។"},
  {id:185,chinese:"眼镜",pinyin:"yǎn jìng",khmer:"វ៉ែនតា",emoji:"👓",category:"daily_items",hsk:3,example_cn:"我需要戴眼镜。",example_km:"ខ្ញុំត្រូវពាក់វ៉ែនតា។"},
  // ===== MARKET (市场) =====
  {id:186,chinese:"市场",pinyin:"shì chǎng",khmer:"ផ្សារ",emoji:"🏪",category:"market",hsk:3,example_cn:"市场里人很多。",example_km:"នៅក្នុងផ្សារមានមនុស្សច្រើន។"},
  {id:187,chinese:"价格",pinyin:"jià gé",khmer:"តម្លៃ",emoji:"🏷️",category:"market",hsk:4,example_cn:"这个的价格是多少？",example_km:"តម្លៃរបស់នេះប៉ុន្មាន?"},
  {id:188,chinese:"打折",pinyin:"dǎ zhé",khmer:"បញ្ចុះតម្លៃ",emoji:"🔖",category:"market",hsk:4,example_cn:"这件衣服打折了。",example_km:"អាវនេះបញ្ចុះតម្លៃហើយ។"},
  // ===== SPORTS (运动) =====
  {id:189,chinese:"足球",pinyin:"zú qiú",khmer:"បាល់ទាត់",emoji:"⚽",category:"sports",hsk:3,example_cn:"我喜欢踢足球。",example_km:"ខ្ញុំចូលចិត្តទាត់បាល់ទាត់។"},
  {id:190,chinese:"篮球",pinyin:"lán qiú",khmer:"បាល់បោះ",emoji:"🏀",category:"sports",hsk:3,example_cn:"他打篮球很厉害。",example_km:"គាត់លេងបាល់បោះពូកែណាស់។"},
  {id:191,chinese:"运动",pinyin:"yùn dòng",khmer:"កីឡា",emoji:"🏃",category:"sports",hsk:2,example_cn:"运动对身体很好。",example_km:"កីឡាល្អសម្រាប់រាងកាយ។"},
  // ===== HEALTH (健康) =====
  {id:192,chinese:"生病",pinyin:"shēng bìng",khmer:"ឈឺ",emoji:"🤒",category:"health",hsk:2,example_cn:"他生病了。",example_km:"គាត់ឈឺហើយ។"},
  {id:193,chinese:"感冒",pinyin:"gǎn mào",khmer:"ផ្ដាសាយ",emoji:"🤧",category:"health",hsk:3,example_cn:"我感冒了。",example_km:"ខ្ញុំផ្ដាសាយហើយ។"},
  {id:194,chinese:"药",pinyin:"yào",khmer:"ថ្នាំ",emoji:"💊",category:"health",hsk:3,example_cn:"吃了药就会好的。",example_km:"ញ៉ាំថ្នាំហើយនឹងជាសះឡើង។"},
  {id:195,chinese:"健康",pinyin:"jiàn kāng",khmer:"សុខភាព",emoji:"💪",category:"health",hsk:3,example_cn:"健康是最重要的。",example_km:"សុខភាពសំខាន់ជាងគេ។"},
  // ===== MORE COMMON WORDS =====
  {id:196,chinese:"中国",pinyin:"zhōng guó",khmer:"ចិន",emoji:"🇨🇳",category:"places",hsk:1,example_cn:"中国是一个大国家。",example_km:"ចិនជាប្រទេសធំ។"},
  {id:197,chinese:"柬埔寨",pinyin:"jiǎn pǔ zhài",khmer:"កម្ពុជា",emoji:"🇰🇭",category:"places",hsk:4,example_cn:"柬埔寨是一个美丽的国家。",example_km:"កម្ពុជាជាប្រទេសស្រស់ស្អាត។"},
  {id:198,chinese:"朋友",pinyin:"péng you",khmer:"មិត្ត",emoji:"👫",category:"greetings",hsk:1,example_cn:"他是我的好朋友。",example_km:"គាត់ជាមិត្តល្អរបស់ខ្ញុំ។"},
  {id:199,chinese:"名字",pinyin:"míng zi",khmer:"ឈ្មោះ",emoji:"📛",category:"greetings",hsk:1,example_cn:"你叫什么名字？",example_km:"អ្នកឈ្មោះអ្វី?"},
  {id:200,chinese:"电话",pinyin:"diàn huà",khmer:"ទូរស័ព្ទ",emoji:"📞",category:"technology",hsk:1,example_cn:"你的电话号码是多少？",example_km:"លេខទូរស័ព្ទអ្នកប៉ុន្មាន?"},
  // ===== MORE VERBS =====
  {id:201,chinese:"去",pinyin:"qù",khmer:"ទៅ",emoji:"➡️",category:"actions",hsk:1,example_cn:"我去学校。",example_km:"ខ្ញុំទៅសាលារៀន។"},
  {id:202,chinese:"来",pinyin:"lái",khmer:"មក",emoji:"⬅️",category:"actions",hsk:1,example_cn:"请过来。",example_km:"សូមអញ្ជើញមក។"},
  {id:203,chinese:"回",pinyin:"huí",khmer:"ត្រឡប់",emoji:"🔙",category:"actions",hsk:1,example_cn:"我要回家了。",example_km:"ខ្ញុំត្រូវត្រឡប់ទៅផ្ទះហើយ។"},
  {id:204,chinese:"想",pinyin:"xiǎng",khmer:"គិត",emoji:"💭",category:"actions",hsk:1,example_cn:"我想去中国。",example_km:"ខ្ញុំចង់ទៅចិន។"},
  {id:205,chinese:"知道",pinyin:"zhī dào",khmer:"ដឹង",emoji:"💡",category:"actions",hsk:1,example_cn:"我知道了。",example_km:"ខ្ញុំដឹងហើយ។"},
  {id:206,chinese:"认识",pinyin:"rèn shi",khmer:"ស្គាល់",emoji:"🤝",category:"actions",hsk:1,example_cn:"很高兴认识你。",example_km:"រីករាយដែលបានស្គាល់អ្នក។"},
  {id:207,chinese:"帮助",pinyin:"bāng zhù",khmer:"ជួយ",emoji:"🤲",category:"actions",hsk:2,example_cn:"谢谢你帮助我。",example_km:"អរគុណដែលជួយខ្ញុំ។"},
  {id:208,chinese:"打电话",pinyin:"dǎ diàn huà",khmer:"ទូរស័ព្ទ​ទៅ",emoji:"📞",category:"actions",hsk:2,example_cn:"我打电话给你。",example_km:"ខ្ញុំទូរស័ព្ទទៅអ្នក។"},
  {id:209,chinese:"等",pinyin:"děng",khmer:"រង់ចាំ",emoji:"⏳",category:"actions",hsk:2,example_cn:"请等一下。",example_km:"សូមរង់ចាំបន្តិច។"},
  {id:210,chinese:"找",pinyin:"zhǎo",khmer:"រក",emoji:"🔍",category:"actions",hsk:2,example_cn:"我在找我的手机。",example_km:"ខ្ញុំកំពុងរកទូរស័ព្ទរបស់ខ្ញុំ។"},
  // ===== MORE NOUNS =====
  {id:211,chinese:"人",pinyin:"rén",khmer:"មនុស្ស",emoji:"👤",category:"greetings",hsk:1,example_cn:"这里有很多人。",example_km:"ទីនេះមានមនុស្សច្រើន។"},
  {id:212,chinese:"东西",pinyin:"dōng xi",khmer:"ឥវ៉ាន់",emoji:"📦",category:"daily_items",hsk:1,example_cn:"你要买什么东西？",example_km:"អ្នកចង់ទិញឥវ៉ាន់អ្វី?"},
  {id:213,chinese:"问题",pinyin:"wèn tí",khmer:"សំណួរ",emoji:"❓",category:"school",hsk:2,example_cn:"你有问题吗？",example_km:"អ្នកមានសំណួរទេ?"},
  {id:214,chinese:"事情",pinyin:"shì qing",khmer:"រឿង",emoji:"📋",category:"actions",hsk:2,example_cn:"我有一件事情要做。",example_km:"ខ្ញុំមានរឿងមួយត្រូវធ្វើ។"},
  {id:215,chinese:"地方",pinyin:"dì fang",khmer:"កន្លែង",emoji:"📍",category:"places",hsk:2,example_cn:"这个地方很美。",example_km:"កន្លែងនេះស្រស់ស្អាតណាស់។"},
  {id:216,chinese:"时间",pinyin:"shí jiān",khmer:"ពេលវេលា",emoji:"⏰",category:"time",hsk:2,example_cn:"时间过得很快。",example_km:"ពេលវេលាកន្លងទៅលឿនណាស់។"},
  {id:217,chinese:"电影",pinyin:"diàn yǐng",khmer:"ភាពយន្ត",emoji:"🎬",category:"technology",hsk:2,example_cn:"我们一起看电影吧。",example_km:"យើងមើលភាពយន្តជាមួយគ្នា។"},
  {id:218,chinese:"音乐",pinyin:"yīn yuè",khmer:"តន្ត្រី",emoji:"🎵",category:"technology",hsk:2,example_cn:"我喜欢听中国音乐。",example_km:"ខ្ញុំចូលចិត្តស្ដាប់តន្ត្រីចិន។"},
  {id:219,chinese:"生日",pinyin:"shēng rì",khmer:"ថ្ងៃកំណើត",emoji:"🎂",category:"time",hsk:2,example_cn:"今天是我的生日。",example_km:"ថ្ងៃនេះជាថ្ងៃកំណើតរបស់ខ្ញុំ។"},
  {id:220,chinese:"礼物",pinyin:"lǐ wù",khmer:"អំណោយ",emoji:"🎁",category:"daily_items",hsk:3,example_cn:"谢谢你的礼物。",example_km:"អរគុណសម្រាប់អំណោយរបស់អ្នក។"},
  // ===== MORE ADJECTIVES =====
  {id:221,chinese:"远",pinyin:"yuǎn",khmer:"ឆ្ងាយ",emoji:"🏔️",category:"adjectives",hsk:2,example_cn:"你家离学校远吗？",example_km:"ផ្ទះអ្នកឆ្ងាយពីសាលារៀនទេ?"},
  {id:222,chinese:"近",pinyin:"jìn",khmer:"ជិត",emoji:"📍",category:"adjectives",hsk:2,example_cn:"超市离这里很近。",example_km:"ផ្សារទំនើបជិតពីទីនេះ។"},
  {id:223,chinese:"长",pinyin:"cháng",khmer:"វែង",emoji:"📏",category:"adjectives",hsk:2,example_cn:"中国的长城很长。",example_km:"កំផែងចិនវែងណាស់។"},
  {id:224,chinese:"短",pinyin:"duǎn",khmer:"ខ្លី",emoji:"📐",category:"adjectives",hsk:3,example_cn:"这条裙子太短了。",example_km:"សំពត់នេះខ្លីពេក។"},
  {id:225,chinese:"胖",pinyin:"pàng",khmer:"ធាត់",emoji:"😊",category:"adjectives",hsk:3,example_cn:"这只猫很胖。",example_km:"ឆ្មានេះធាត់ណាស់។"},
  {id:226,chinese:"瘦",pinyin:"shòu",khmer:"ស្គម",emoji:"🙂",category:"adjectives",hsk:3,example_cn:"他太瘦了。",example_km:"គាត់ស្គមពេក។"},
  {id:227,chinese:"高",pinyin:"gāo",khmer:"ខ្ពស់",emoji:"📈",category:"adjectives",hsk:1,example_cn:"他很高。",example_km:"គាត់ខ្ពស់ណាស់។"},
  {id:228,chinese:"矮",pinyin:"ǎi",khmer:"ទាប",emoji:"📉",category:"adjectives",hsk:3,example_cn:"这棵树很矮。",example_km:"ដើមឈើនេះទាបណាស់។"},
  {id:229,chinese:"干净",pinyin:"gān jìng",khmer:"ស្អាត",emoji:"✨",category:"adjectives",hsk:3,example_cn:"这个房间很干净。",example_km:"បន្ទប់នេះស្អាតណាស់។"},
  {id:230,chinese:"容易",pinyin:"róng yì",khmer:"ងាយ",emoji:"👌",category:"adjectives",hsk:3,example_cn:"这道题很容易。",example_km:"លំហាត់នេះងាយណាស់។"},
  {id:231,chinese:"难",pinyin:"nán",khmer:"ពិបាក",emoji:"😰",category:"adjectives",hsk:2,example_cn:"中文很难学。",example_km:"ភាសាចិនពិបាករៀន។"},
  {id:232,chinese:"重要",pinyin:"zhòng yào",khmer:"សំខាន់",emoji:"⚠️",category:"adjectives",hsk:3,example_cn:"健康很重要。",example_km:"សុខភាពសំខាន់ណាស់។"},
  // ===== MORE USEFUL WORDS =====
  {id:233,chinese:"中文",pinyin:"zhōng wén",khmer:"ភាសាចិន",emoji:"🇨🇳",category:"school",hsk:1,example_cn:"我在学中文。",example_km:"ខ្ញុំកំពុងរៀនភាសាចិន។"},
  {id:234,chinese:"高棉语",pinyin:"gāo mián yǔ",khmer:"ភាសាខ្មែរ",emoji:"🇰🇭",category:"school",hsk:5,example_cn:"你会说高棉语吗？",example_km:"អ្នកចេះនិយាយភាសាខ្មែរទេ?"},
  {id:235,chinese:"厉害",pinyin:"lì hai",khmer:"ពូកែ",emoji:"💪",category:"adjectives",hsk:3,example_cn:"你真厉害！",example_km:"អ្នកពូកែណាស់!"},
  {id:236,chinese:"加油",pinyin:"jiā yóu",khmer:"សូមប្រឹង",emoji:"💪",category:"greetings",hsk:3,example_cn:"加油！你可以的！",example_km:"សូមប្រឹង! អ្នកធ្វើបាន!"},
  {id:237,chinese:"钟",pinyin:"zhōng",khmer:"នាឡិកា",emoji:"🕐",category:"time",hsk:2,example_cn:"现在八点钟。",example_km:"ឥឡូវម៉ោង ៨។"},
  {id:238,chinese:"路",pinyin:"lù",khmer:"ផ្លូវ",emoji:"🛤️",category:"places",hsk:2,example_cn:"这条路很长。",example_km:"ផ្លូវនេះវែងណាស់។"},
  {id:239,chinese:"雨",pinyin:"yǔ",khmer:"ភ្លៀង",emoji:"🌧️",category:"weather",hsk:2,example_cn:"柬埔寨雨季雨很多。",example_km:"នៅកម្ពុជារដូវភ្លៀងមានភ្លៀងច្រើន។"},
  {id:240,chinese:"饭",pinyin:"fàn",khmer:"បាយ",emoji:"🍚",category:"food",hsk:1,example_cn:"你吃饭了吗？",example_km:"អ្នកញ៉ាំបាយហើយឬនៅ?"},
  {id:241,chinese:"先生",pinyin:"xiān sheng",khmer:"លោក",emoji:"🤵",category:"greetings",hsk:1,example_cn:"先生，您好。",example_km:"សួស្តី លោក។"},
  {id:242,chinese:"小姐",pinyin:"xiǎo jiě",khmer:"កញ្ញា",emoji:"👩",category:"greetings",hsk:1,example_cn:"小姐，请问…",example_km:"កញ្ញា សូមសួរ..."},
  {id:243,chinese:"公司",pinyin:"gōng sī",khmer:"ក្រុមហ៊ុន",emoji:"🏢",category:"places",hsk:2,example_cn:"我在公司上班。",example_km:"ខ្ញុំធ្វើការនៅក្រុមហ៊ុន។"},
  {id:244,chinese:"护照",pinyin:"hù zhào",khmer:"លិខិតឆ្លងដែន",emoji:"🛂",category:"daily_items",hsk:4,example_cn:"请出示你的护照。",example_km:"សូមបង្ហាញលិខិតឆ្លងដែនរបស់អ្នក។"},
  {id:245,chinese:"签证",pinyin:"qiān zhèng",khmer:"ទិដ្ឋាការ",emoji:"📃",category:"daily_items",hsk:4,example_cn:"我需要办签证。",example_km:"ខ្ញុំត្រូវការធ្វើទិដ្ឋាការ។"},
  {id:246,chinese:"零",pinyin:"líng",khmer:"សូន្យ",emoji:"0️⃣",category:"numbers",hsk:1,example_cn:"零度以下很冷。",example_km:"ក្រោមសូន្យដឺក្រេត្រជាក់ណាស់។"},
  {id:247,chinese:"四",pinyin:"sì",khmer:"បួន",emoji:"4️⃣",category:"numbers",hsk:1,example_cn:"我有四个朋友。",example_km:"ខ្ញុំមានមិត្តបួននាក់។"},
  {id:248,chinese:"五",pinyin:"wǔ",khmer:"ប្រាំ",emoji:"5️⃣",category:"numbers",hsk:1,example_cn:"我等了五分钟。",example_km:"ខ្ញុំរង់ចាំប្រាំនាទី។"},
  {id:249,chinese:"六",pinyin:"liù",khmer:"ប្រាំមួយ",emoji:"6️⃣",category:"numbers",hsk:1,example_cn:"六月天气很热。",example_km:"ខែប្រាំមួយអាកាសធាតុក្ដៅ។"},
  {id:250,chinese:"七",pinyin:"qī",khmer:"ប្រាំពីរ",emoji:"7️⃣",category:"numbers",hsk:1,example_cn:"一个星期有七天。",example_km:"មួយសប្ដាហ៍មានប្រាំពីរថ្ងៃ។"},
  {id:251,chinese:"八",pinyin:"bā",khmer:"ប្រាំបី",emoji:"8️⃣",category:"numbers",hsk:1,example_cn:"八是中国的幸运数字。",example_km:"ប្រាំបីជាលេខសំណាងរបស់ចិន។"},
  {id:252,chinese:"九",pinyin:"jiǔ",khmer:"ប្រាំបួន",emoji:"9️⃣",category:"numbers",hsk:1,example_cn:"九点上课。",example_km:"ម៉ោងប្រាំបួនចូលរៀន។"},
  {id:253,chinese:"万",pinyin:"wàn",khmer:"ម៉ឺន",emoji:"🔢",category:"numbers",hsk:3,example_cn:"一万块钱不少了。",example_km:"មួយម៉ឺនយាន់មិនតិចទេ។"},
  {id:254,chinese:"右",pinyin:"yòu",khmer:"ស្ដាំ",emoji:"👉",category:"actions",hsk:2,example_cn:"向右转。",example_km:"បត់ស្ដាំ។"},
  {id:255,chinese:"左",pinyin:"zuǒ",khmer:"ឆ្វេង",emoji:"👈",category:"actions",hsk:2,example_cn:"向左转。",example_km:"បត់ឆ្វេង។"},
  {id:256,chinese:"前面",pinyin:"qián miàn",khmer:"ខាងមុខ",emoji:"⬆️",category:"actions",hsk:2,example_cn:"学校在前面。",example_km:"សាលារៀននៅខាងមុខ។"},
  {id:257,chinese:"后面",pinyin:"hòu miàn",khmer:"ខាងក្រោយ",emoji:"⬇️",category:"actions",hsk:2,example_cn:"停车场在后面。",example_km:"កន្លែងចតឡាននៅខាងក្រោយ។"},
  {id:258,chinese:"上面",pinyin:"shàng miàn",khmer:"ខាងលើ",emoji:"☝️",category:"actions",hsk:2,example_cn:"书在桌子上面。",example_km:"សៀវភៅនៅលើតុ។"},
  {id:259,chinese:"下面",pinyin:"xià miàn",khmer:"ខាងក្រោម",emoji:"👇",category:"actions",hsk:2,example_cn:"猫在桌子下面。",example_km:"ឆ្មានៅក្រោមតុ។"},
  {id:260,chinese:"里面",pinyin:"lǐ miàn",khmer:"ខាងក្នុង",emoji:"📥",category:"actions",hsk:2,example_cn:"人在房间里面。",example_km:"មនុស្សនៅក្នុងបន្ទប់។"},
  {id:261,chinese:"外面",pinyin:"wài miàn",khmer:"ខាងក្រៅ",emoji:"📤",category:"actions",hsk:2,example_cn:"外面下雨了。",example_km:"ខាងក្រៅភ្លៀងធ្លាក់ហើយ។"},
  {id:262,chinese:"旁边",pinyin:"páng biān",khmer:"ក្បែរ",emoji:"➡️",category:"actions",hsk:2,example_cn:"银行在学校旁边。",example_km:"ធនាគារនៅក្បែរសាលារៀន។"},
  // ===== MORE USEFUL PHRASES =====
  {id:263,chinese:"怎么",pinyin:"zěn me",khmer:"យ៉ាងម៉េច",emoji:"❓",category:"greetings",hsk:1,example_cn:"你怎么了？",example_km:"អ្នកយ៉ាងម៉េចហើយ?"},
  {id:264,chinese:"为什么",pinyin:"wèi shén me",khmer:"ហេតុអ្វី",emoji:"🤔",category:"greetings",hsk:2,example_cn:"你为什么迟到？",example_km:"ហេតុអ្វីបានជាអ្នកមកយឺត?"},
  {id:265,chinese:"什么",pinyin:"shén me",khmer:"អ្វី",emoji:"❓",category:"greetings",hsk:1,example_cn:"这是什么？",example_km:"នេះជាអ្វី?"},
  {id:266,chinese:"哪里",pinyin:"nǎ lǐ",khmer:"ឯណា",emoji:"📍",category:"greetings",hsk:1,example_cn:"你家在哪里？",example_km:"ផ្ទះអ្នកនៅឯណា?"},
  {id:267,chinese:"谁",pinyin:"shéi",khmer:"នរណា",emoji:"👤",category:"greetings",hsk:1,example_cn:"他是谁？",example_km:"គាត់ជានរណា?"},
  {id:268,chinese:"多少",pinyin:"duō shao",khmer:"ប៉ុន្មាន",emoji:"🔢",category:"greetings",hsk:1,example_cn:"这个多少钱？",example_km:"នេះថ្លៃប៉ុន្មាន?"},
  // ===== ADDITIONAL WORDS FOR RICHNESS =====
  {id:269,chinese:"春天",pinyin:"chūn tiān",khmer:"រដូវផ្ការីក",emoji:"🌸",category:"nature",hsk:3,example_cn:"春天花开了。",example_km:"រដូវផ្ការីកផ្កាបានរីក។"},
  {id:270,chinese:"夏天",pinyin:"xià tiān",khmer:"រដូវក្ដៅ",emoji:"☀️",category:"nature",hsk:3,example_cn:"夏天很热。",example_km:"រដូវក្ដៅក្ដៅណាស់។"},
  {id:271,chinese:"秋天",pinyin:"qiū tiān",khmer:"រដូវស្លឹកឈើជ្រុះ",emoji:"🍂",category:"nature",hsk:3,example_cn:"秋天叶子变黄了。",example_km:"រដូវស្លឹកឈើជ្រុះស្លឹកប្រែពណ៌លឿង។"},
  {id:272,chinese:"冬天",pinyin:"dōng tiān",khmer:"រដូវរងារ",emoji:"⛄",category:"nature",hsk:3,example_cn:"冬天要穿厚衣服。",example_km:"រដូវរងារត្រូវពាក់អាវក្រាស់។"},
  {id:273,chinese:"天",pinyin:"tiān",khmer:"ថ្ងៃ / មេឃ",emoji:"🌤️",category:"nature",hsk:1,example_cn:"今天天很蓝。",example_km:"ថ្ងៃនេះមេឃខៀវណាស់។"},
  {id:274,chinese:"地",pinyin:"dì",khmer:"ដី",emoji:"🌍",category:"nature",hsk:2,example_cn:"地上有很多落叶。",example_km:"នៅលើដីមានស្លឹកឈើជ្រុះច្រើន។"},
  {id:275,chinese:"能",pinyin:"néng",khmer:"អាច",emoji:"💪",category:"actions",hsk:1,example_cn:"你能帮我吗？",example_km:"អ្នកអាចជួយខ្ញុំបានទេ?"},
  {id:276,chinese:"会",pinyin:"huì",khmer:"ចេះ",emoji:"✅",category:"actions",hsk:1,example_cn:"我会说中文。",example_km:"ខ្ញុំចេះនិយាយភាសាចិន។"},
  {id:277,chinese:"可以",pinyin:"kě yǐ",khmer:"អាច / បាន",emoji:"👌",category:"actions",hsk:1,example_cn:"可以进来吗？",example_km:"អាចចូលមកបានទេ?"},
  {id:278,chinese:"吗",pinyin:"ma",khmer:"ទេ (សំណួរ)",emoji:"❓",category:"greetings",hsk:1,example_cn:"你好吗？",example_km:"អ្នកសុខសប្បាយទេ?"},
  {id:279,chinese:"了",pinyin:"le",khmer:"ហើយ",emoji:"✔️",category:"greetings",hsk:1,example_cn:"我吃饭了。",example_km:"ខ្ញុំញ៉ាំបាយហើយ។"},
  {id:280,chinese:"很",pinyin:"hěn",khmer:"ណាស់",emoji:"💯",category:"adjectives",hsk:1,example_cn:"今天很热。",example_km:"ថ្ងៃនេះក្ដៅណាស់។"},
];

// Write the file
const outPath = path.join(__dirname, '..', 'data', 'vocabulary.json');
fs.writeFileSync(outPath, JSON.stringify(words, null, 2), 'utf-8');
console.log(`Generated ${words.length} words to ${outPath}`);
